### ISSUE TITLE
KeyNotFoundException: The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by sankar2389** [theodor349/4P-Chess#1]
While I ran this project in my unity 2019 version, I got the following errors

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
CharacterController.GetSprite (Character c) (at Assets/Scripts/Controllers/CharacterController.cs:88)
CharacterController.DrawCharacter (Character c) (at Assets/Scripts/Controllers/CharacterController.cs:42)
CharacterController.DrawCharacteres () (at Assets/Scripts/Controllers/CharacterController.cs:29)
CharacterController.Start () (at Assets/Scripts/Controllers/CharacterController.cs:20)

**Comment by theodor349** [comment]
Hi, I have just uploaded a fix and updated to Unity 2019.2.0b9

But if you try to debug it you will find that at line 88 in the CharacterController script it tries to find a sprite in the dictionary "characterSprites". The key it looks for is in all caps, whereas all the keys in the dictionary only the first character is in caps. This can be solved by renaming all the sprites under "/resources/sprites/characters" with all caps characters.

**Comment by sankar2389** [comment]
Thanks, after renaming them it works perfectly. 👍
